name: Deploy Calculator to GitHub Pages

on:
  push:
    branches:
<<<<<<< HEAD
      - main  # Change this if your default is something else
=======
      - main  # Change this if your default branch is something else
>>>>>>> 8fa01775918bba33413451595bcd88c03e2179e1

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload static files
        uses: actions/upload-pages-artifact@v2
        with:
          path: .  # Current directory contains your index.html, style.css, etc.

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
